import "@/app/globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { redirect, useRouter } from "next/navigation";
import Navbar from "@/components/app/nav-bar";
import { useSession } from "next-auth/react";
import { getServerSession } from "next-auth/next";
import {  validateRequest } from "@/lib/auth";
import ReactQueryProvider from "@/components/app/providers/react-query-provider";

export const metadata: Metadata = {
  title: "biddropper - Dashboard",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  contractor,
  user,
}: {
  children: React.ReactNode;
  contractor: React.ReactNode;
  user: React.ReactNode;
}) {
  const {session} = await validateRequest();

  if (!session) redirect("/login");

  // TODO: use trpc and query owned companies when db schema is updated
  const isContractor = false;

  console.log(isContractor);
  return (
    <main className="h-full w-full">
      <div className="relative h-full w-full ">
        <Navbar className="fixed top-0 z-30 w-full bg-card/50 backdrop-blur-md" />
        {isContractor ? contractor : user}
      </div>
    </main>
  );
}
