export const serviceCategories = [
	{ label: "Concrete Contractors", value: "concrete-contractors" },
	{ label: "Piano Moving & Tuning", value: "piano-moving-tuning" },
	{ label: "Closet & Storage Solutions", value: "closet-storage-solutions" },
	{ label: "Interlocking Stone", value: "interlocking-stone" },
	{ label: "Awnings & Canopies", value: "awnings-canopies" },
	{ label: "Renewable Energy", value: "renewable-energy" },
	{ label: "Solar Water Heating", value: "solar-water-heating" },
	{ label: "Furniture", value: "furniture" },
	{
		label: "Organizing Products & Services",
		value: "organizing-products-services",
	},
	{ label: "Framing", value: "framing" },
	{ label: "Appliance Repair", value: "appliance-repair" },
	{ label: "Tile and Grout Cleaning", value: "tile-and-grout-cleaning" },
	{ label: "Decks", value: "decks" },
	{ label: "Landscape Architects", value: "landscape-architects" },
	{ label: "Tree Service", value: "tree-service" },
	{ label: "Drapery & Curtains", value: "drapery-curtains" },
	{ label: "Tile & Stone Contractors", value: "tile-stone-contractors" },
	{
		label: "Swimming Pools, Spas & Hot Tubs",
		value: "swimming-pools-spas-hot-tubs",
	},
	{ label: "Duct Cleaning", value: "duct-cleaning" },
	{
		label: "Skylight Installation & Repair",
		value: "skylight-installation-repair",
	},
	{ label: "Lawn Maintenance", value: "lawn-maintenance" },
	{ label: "Siding", value: "siding" },
	{
		label: "Kitchen Planning & Renovation",
		value: "kitchen-planning-renovation",
	},
	{ label: "Mold Detection & Removal", value: "mold-detection-removal" },
	{ label: "Shutters & Blinds", value: "shutters-blinds" },
	{ label: "Blinds Cleaning & Repairing", value: "blinds-cleaning-repairing" },
	{ label: "Appliance Retailers", value: "appliance-retailers" },
	{ label: "Woodworking", value: "woodworking" },
	{ label: "Foundations", value: "foundations" },
	{ label: "Drafting Service", value: "drafting-service" },
	{ label: "Chimney Build & Repair", value: "chimney-build-repair" },
	{ label: "Gazebos & Sheds", value: "gazebos-sheds" },
	{ label: "Solar Panels", value: "solar-panels" },
	{ label: "Condominium Renovations", value: "condominium-renovations" },
	{ label: "Masonry & Bricklaying", value: "masonry-bricklaying" },
	{ label: "Junk Removal", value: "junk-removal" },
	{
		label: "Bathroom & Kitchen - Fixtures & Accessories",
		value: "bathroom-kitchen-fixtures-accessories",
	},
	{
		label: "Building Supplies and Hardware",
		value: "building-supplies-and-hardware",
	},
	{ label: "Railings", value: "railings" },
	{ label: "Design/Build", value: "design-build" },
	{
		label: "Paint & Wallpaper Contractors",
		value: "paint-wallpaper-contractors",
	},
	{ label: "Interior Design", value: "interior-design" },
	{ label: "Drain Services", value: "drain-services" },
	{ label: "Snow Removal", value: "snow-removal" },
	{ label: "General Contractors", value: "general-contractors" },
	{ label: "Demolition", value: "demolition" },
	{
		label: "Garage Design & Organization",
		value: "garage-design-organization",
	},
	{ label: "Locks & Locksmiths", value: "locks-locksmiths" },
	{ label: "Plumbing", value: "plumbing" },
	{ label: "Window & Gutter Cleaning", value: "window-gutter-cleaning" },
	{
		label: "Kitchen & Bathroom - Cabinets & Design",
		value: "kitchen-bathroom-cabinets-design",
	},
	{ label: "House Cleaning Exteriors", value: "house-cleaning-exteriors" },
	{
		label: "Landscape Contractors & Designers",
		value: "landscape-contractors-designers",
	},
	{ label: "Trim and Moldings", value: "trim-and-moldings" },
	{ label: "Mirrors & Glass", value: "mirrors-glass" },
	{ label: "Self Storage", value: "self-storage" },
	{ label: "Carpenters", value: "carpenters" },
	{ label: "Green Products & Services", value: "green-products-services" },
	{ label: "Cabinetry & Millwork", value: "cabinetry-millwork" },
	{ label: "Bathroom Renovation", value: "bathroom-renovation" },
	{
		label: "Carpet & Rug Cleaning & Repairing",
		value: "carpet-rug-cleaning-repairing",
	},
	{ label: "Satellite Sales & Service", value: "satellite-sales-service" },
	{ label: "Electronic Repairs", value: "electronic-repairs" },
	{ label: "Fireplace Mantels", value: "fireplace-mantels" },
	{
		label: "Furniture Designers & Custom Builders",
		value: "furniture-designers-custom-builders",
	},
	{ label: "Home Inspection", value: "home-inspection" },
	{
		label: "Asbestos, Lead, and Radon Removal",
		value: "asbestos-lead-and-radon-removal",
	},
	{ label: "Alarm Systems", value: "alarm-systems" },
	{ label: "Floor Retailers", value: "floor-retailers" },
	{ label: "Countertops", value: "countertops" },
	{ label: "Furniture Refinish & Repair", value: "furniture-refinish-repair" },
	{ label: "Paving Contractors", value: "paving-contractors" },
	{ label: "Sprinkler Systems", value: "sprinkler-systems" },
	{ label: "Weed Control", value: "weed-control" },
	{ label: "Stair Builders", value: "stair-builders" },
	{ label: "Handyman Services", value: "handyman-services" },
	{ label: "Basement Renovation", value: "basement-renovation" },
	{ label: "Architects", value: "architects" },
	{ label: "Lighting", value: "lighting" },
	{ label: "Historical Restoration", value: "historical-restoration" },
	{ label: "Garage Doors & Hardware", value: "garage-doors-hardware" },
	{ label: "Carpet & Rug Retailers", value: "carpet-rug-retailers" },
	{ label: "Fences & Gates", value: "fences-gates" },
	{ label: "Vacuum Sales & Service", value: "vacuum-sales-service" },
	{ label: "Home Staging", value: "home-staging" },
	{ label: "Home Automation", value: "home-automation" },
	{
		label: "Computer Repairs and Support",
		value: "computer-repairs-and-support",
	},
	{
		label: "Electrical Vehicle Charging",
		value: "electrical-vehicle-charging",
	},
	{ label: "Roofing", value: "roofing" },
	{ label: "Drainage Contractors", value: "drainage-contractors" },
	{ label: "Home Office Renovation", value: "home-office-renovation" },
	{
		label: "Elevators, Lifts & Ramps Installation & Service",
		value: "elevators-lifts-ramps-installation-service",
	},
	{ label: "Excavation", value: "excavation" },
	{
		label: "Sunrooms, Solariums & Greenhouses",
		value: "sunrooms-solariums-greenhouses",
	},
	{ label: "Drywall Contractors", value: "drywall-contractors" },
	{ label: "Waterproofing", value: "waterproofing" },
	{ label: "Gas Line Installation", value: "gas-line-installation" },
	{ label: "Moving & Storage", value: "moving-storage" },
	{
		label: "Drapery & Upholstery Cleaning",
		value: "drapery-upholstery-cleaning",
	},
	{ label: "Floor Laying & Refinishing", value: "floor-laying-refinishing" },
	{ label: "Chimney Sweeps", value: "chimney-sweeps" },
	{ label: "Stucco", value: "stucco" },
	{ label: "House & Apartment Cleaning", value: "house-apartment-cleaning" },
	{ label: "Surveyors", value: "surveyors" },
	{
		label: "Windows & Doors Installation & Service",
		value: "windows-doors-installation-service",
	},
	{ label: "Heating & Air Conditioning", value: "heating-air-conditioning" },
	{
		label: "Water Filtration & Purification",
		value: "water-filtration-purification",
	},
	{ label: "Insulation", value: "insulation" },
	{ label: "Decorative Concrete", value: "decorative-concrete" },
	{ label: "Landscape Lighting", value: "landscape-lighting" },
	{ label: "Structural Engineering", value: "structural-engineering" },
	{ label: "Fireplaces", value: "fireplaces" },
	{ label: "Pest & Animal Control", value: "pest-animal-control" },
	{ label: "Electricians", value: "electricians" },
	{
		label: "Fire & Water Damage Restoration",
		value: "fire-water-damage-restoration",
	},
	{ label: "Renovation Cleaning", value: "renovation-cleaning" },
	{ label: "Garden Maintenance", value: "garden-maintenance" },
	{ label: "Interior Decorators", value: "interior-decorators" },
	{
		label: "Septic Tank Cleaning, Repair & Installation",
		value: "septic-tank-cleaning-repair-installation",
	},
	{ label: "Renovation Advisors", value: "renovation-advisors" },
	{ label: "Carpet Installers", value: "carpet-installers" },
	{ label: "Home Additions", value: "home-additions" },
	{ label: "Art Metal Work", value: "art-metal-work" },
	{ label: "Plastering", value: "plastering" },
	{ label: "Builders", value: "builders" },
	{ label: "BBQ Equipment & Service", value: "bbq-equipment-service" },
	{ label: "Design/Project Management", value: "design-project-management" },
	{ label: "Tuck Pointing", value: "tuck-pointing" },
	{ label: "Game Rooms, Entertainment", value: "game-rooms-entertainment" },
	{ label: "Home Theater", value: "home-theater" },
	{ label: "Upholsterers", value: "upholsterers" },
	{ label: "Gutters & Eavestroughs", value: "gutters-eavestroughs" },
	{ label: "Furniture Rental", value: "furniture-rental" },
];

export const industryValues = serviceCategories.map((category) => category.value);