import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
	server: {
		NODE_ENV: z.enum(["development", "test", "production"]),
		PLANETSCALE_HOST_NAME: z.string().min(1),
		PLANETSCALE_USERNAME: z.string().min(1),
		PLANETSCALE_PASSWORD: z.string().min(1),
		PLANETSCALE_DATABASE_NAME: z.string().min(1),
		PLANETSCALE_DATABASE_URL: z.string().url(),
		CLERK_SECRET_KEY: z.string().min(1),
		CLERK_AUTH_WEBHOOK_SECRET: z.string().min(1),
		CLERK_ORGANIZATION_WEBHOOK_SECRET: z.string().min(1),
		CLERK_COMMUNICATION_WEBHOOK_SECRET: z.string().min(1),
		CLERK_SESSION_WEBHOOK_SECRET: z.string().min(1),
		UPLOADTHING_SECRET: z.string().min(1),
		UPLOADTHING_APP_ID: z.string().min(1),
		GOOGLE_MAPS_JAVASCRIPT_API_KEY: z.string().min(1),
		NEXTAUTH_SECRET: z.string().min(1),
		GITHUB_CLIENT_ID: z.string().min(1),
		GITHUB_CLIENT_SECRET: z.string().min(1),
		GOOGLE_CLIENT_ID: z.string().min(1),
		RESEND_API_KEY: z.string().min(1),
		GOOGLE_CLIENT_SECRET: z.string().min(1),
		NEXTAUTH_URL: z.string().url(),
	},

	client: {
		NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: z.string().min(1),
		NEXT_PUBLIC_APP_URL: z.string().url(),
		NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL: z.string().min(1),
		NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL: z.string().min(1),
		NEXT_PUBLIC_CLERK_SIGN_UP_URL: z.string().min(1),
		NEXT_PUBLIC_CLERK_SIGN_IN_URL: z.string().min(1),
	},

	runtimeEnv: {
		NEXTAUTH_URL: process.env.NEXTAUTH_URL,
		RESEND_API_KEY: process.env.RESEND_API_KEY,
		NODE_ENV: process.env.NODE_ENV,
		PLANETSCALE_HOST_NAME: process.env.PLANETSCALE_HOST_NAME,
		PLANETSCALE_USERNAME: process.env.PLANETSCALE_USERNAME,
		PLANETSCALE_PASSWORD: process.env.PLANETSCALE_PASSWORD,
		PLANETSCALE_DATABASE_URL: process.env.PLANETSCALE_DATABASE_URL,
		PLANETSCALE_DATABASE_NAME: process.env.PLANETSCALE_DATABASE_NAME,
		CLERK_SECRET_KEY: process.env.CLERK_SECRET_KEY,
		CLERK_AUTH_WEBHOOK_SECRET: process.env.CLERK_AUTH_WEBHOOK_SECRET,
		CLERK_ORGANIZATION_WEBHOOK_SECRET:
			process.env.CLERK_ORGANIZATION_WEBHOOK_SECRET,
		NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:
			process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY,
		CLERK_COMMUNICATION_WEBHOOK_SECRET:
			process.env.CLERK_COMMUNICATION_WEBHOOK_SECRET,
		CLERK_SESSION_WEBHOOK_SECRET: process.env.CLERK_SESSION_WEBHOOK_SECRET,
		NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
		NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL:
			process.env.NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL,
		NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL:
			process.env.NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL,
		NEXT_PUBLIC_CLERK_SIGN_UP_URL: process.env.NEXT_PUBLIC_CLERK_SIGN_UP_URL,
		NEXT_PUBLIC_CLERK_SIGN_IN_URL: process.env.NEXT_PUBLIC_CLERK_SIGN_IN_URL,
		UPLOADTHING_SECRET: process.env.UPLOADTHING_SECRET,
		GOOGLE_MAPS_JAVASCRIPT_API_KEY: process.env.GOOGLE_MAPS_JAVASCRIPT_API_KEY,
		UPLOADTHING_APP_ID: process.env.UPLOADTHING_APP_ID,
		NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,
		GITHUB_CLIENT_ID: process.env.GITHUB_CLIENT_ID,
		GITHUB_CLIENT_SECRET: process.env.GITHUB_CLIENT_SECRET,
		GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
		GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
	},

	skipValidation: !!process.env.SKIP_ENV_VALIDATION,
});
